theme = "apollo"
taxonomies = [{ name = "tags" }]

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14

# base_url = "https://fettenderimakes.games"
base_url = "https://fettenderi.github.io"
title = "Marco Manganaro"

compile_sass = true
minify_html = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
toc = true
theme = "toggle"
favicon = "/icon/favicon.png"
socials = [
  { name = "linktree", url = "https://linktr.ee/fettenderi", icon = "linktree" },
  { name = "itch.io", url = "https://fettenderi.itch.io", icon = "itchio" },
  { name = "github", url = "https://github.com/Fettenderi", icon = "github" },
  { name = "linkedin", url = "https://www.linkedin.com/in/marco-manganaro/", icon = "linkedin" },
]
menu = [
    { name = "/games", url = "/games", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
]

